# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- test

pool:
  vmImage: ubuntu-latest

variables:
- group: Frontend
- name: profile
  value: $[replace(variables['Build.SourceBranchName'], 'main', 'production')]

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g nx
    npm install
    npm run build:$(profile)
    tree -L dist/
  displayName: 'npm install and build'
  workingDirectory: app

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'app/dist/apps/crypto-mayhem-frontend'
    skip_app_build: true
    skip_api_build: true
    is_static_export: true
    azure_static_web_apps_api_token: $(deployment_token)
    production_branch: 'main'
