version: "3.9"
services:
  rpc:
    build: 
      context: ./docker/rpc/
    depends_on: 
      - nginx
  nginx:
    build: 
      context: ../../..
      dockerfile: ./pipelines/manual/hook/docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      
