version: '3.9'
services:
  rpc_chain:
    container_name: 'rpc_chain'
    build: 
      context: .
      dockerfile: ./docker/rpc/stage/Dockerfile
  rpc_db:
    container_name: 'rpc_db'
    image: postgres:13.6-alpine
    env_file: ./config/rpc/db.env
    depends_on:
      - rpc_chain
    networks:
      default:
        aliases:
          - host.docker.internal
          - database
  rpc_scan:
    container_name: 'rpc_scan'
    image: blockscout/blockscout:latest
    env_file: ./config/rpc/scan.env
    command: mix do ecto.create, ecto.migrate, phx.server
    restart: always
    depends_on:
      - rpc_db
  proxy:
    container_name: 'proxy'
    build:
      context: ./docker/proxy
    depends_on:
      - rpc_scan
  nginx:
    container_name: 'nginx'
    build: 
      context: ../../..
      dockerfile: ./pipelines/manual/hook/docker/nginx/Dockerfile
    volumes:
      - assets-contracts:/var/www/app.test.cryptomayhem.io/html/assets/contracts/
    depends_on:
      - proxy
    ports:
      - 443:443
  deploy:
    container_name: 'deploy'
    build:
      context: ../../../contracts
      dockerfile: ../pipelines/manual/hook/docker/deploy/stage/Dockerfile
    volumes:
      - assets-contracts:/contracts/export/
    depends_on:
      - nginx

volumes:
  assets-contracts:
