version: "3.9"
services:
  rpc:
    build: 
      context: ./docker/rpc/
  proxy:
    build:
      context: ./docker/proxy
    depends_on:
      - rpc
  nginx:
    build: 
      context: ../../..
      dockerfile: ./pipelines/manual/hook/docker/nginx/Dockerfile
    depends_on:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      
