version: '3.9'
services:
  rpc_chain:
    container_name: 'rpc_chain'
    build: 
      context: .
      dockerfile: ./docker/rpc/local/Dockerfile
    ports:
      - 8545:8545
  rpc_db:
    container_name: 'rpc_db'
    image: postgres:13.6-alpine
    env_file: ./config/rpc/db.env
    depends_on:
      - rpc_chain
    networks:
      default:
        aliases:
          - host.docker.internal
          - database
  rpc_scan:
    container_name: 'rpc_scan'
    image: blockscout/blockscout:latest
    env_file: ./config/rpc/scan.env
    command: mix do ecto.create, ecto.migrate, phx.server
    restart: always
    depends_on:
      - rpc_db
    ports:
      - 4000:4000
  deploy:
    container_name: 'deploy'
    build:
      context: ../../../contracts
      dockerfile: ../pipelines/manual/hook/docker/deploy/local/Dockerfile
    volumes:
      - ../../../app/libs/crypto-mayhem/assets/contracts/:/contracts/export/
    depends_on:
      - rpc_scan
